language: objective-c

addons:
  ssh_known_hosts:
    - github.com
    - bitbucket.org

notifications:
  email:
    on_success: never
    on_failure: change

before_install:
  # -  if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install mercurial; else brew install mercurial; fi
  - export TEST_GIT_BIN=$(which git)
  - export TEST_SVN_BIN=$(which svn)
  - export TEST_HG_BIN=$(which hg)
  - echo "use $TEST_GIT_BIN, $TEST_SVN_BIN, $TEST_HG_BIN"
  - export SKIP_HG_TESTS=true
  - export SKIP_SVN_TESTS=true

before_script:
  - 'echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config'

script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'
